# MythicMOTD Configuration
# Plugin created by Spectrasonic

server_motd:
    line_1: "<c><gradient:#3f368e:#ffdd5c><b>Mythic MOTD</b></gradient></c>"
    line_2: "<c><rainbow><b>MiniMessage</rainbow> <#a8baff><b>Support</b></#a8baff></c>"

messages:
    reload: "Config reloaded!"